version: "2"

services:

  contractdb:
    build: ./contractdb
    container_name: contractdb
    hostname: contractdb
    privileged: true
    tty: true
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "contractdb"
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432
