CREATE TABLE IF NOT EXISTS user
(
    user_id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    full_name TEXT NOT NULL,
    balance NUMERIC(19,4) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS contract
(
    contract_id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    issuer_id BIGINT NOT NULL,
    signer_id BIGINT NOT NULL,
    note TEXT NOT NULL,
    amount NUMERIC(19,4) NOT NULL,
    signed BOOLEAN NOT NULL DEFAULT FALSE
);

